
services:
  ans_database:
    image: postgres:15-alpine
    container_name: ans_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ans_database
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: